### ISSUE TITLE
Loosen pip requirement for click

### ISSUE THREAD

**Issue by MHendricks** [altendky/qt-tools#10]
In setup.cfg the click requirement is limited to only the 7 versions of click(`click~=7.0`). I'm running into a dependency conflict with black that requires `click>=8.0.0`.

Would it be possible to change the click dependency to `click>=7.0` to allow for the latest releases? The other qt pip packages allow for any version of click.

Here is the pipdeptree report on my windows system using python 3.9.13.
```
$ pipdeptree -rp click
Warning!!! Possibly conflicting dependencies found:
* qt5-tools==5.15.2.1.2
 - click [required: ~=7.0, installed: 8.1.3]
click==8.1.3
  - black==22.6.0 [requires: click>=8.0.0]
  - pyqt5-plugins==5.15.4.2.2 [requires: click]
    - pyqt5-tools==5.15.4.3.2 [requires: pyqt5-plugins>=5.15.4.2.2,<5.15.4.3]
  - pyqt5-tools==5.15.4.3.2 [requires: click]
  - qt5-tools==5.15.2.1.2 [requires: click~=7.0]
    - pyqt5-plugins==5.15.4.2.2 [requires: qt5-tools>=5.15.2.1.2,<5.15.2.2]
      - pyqt5-tools==5.15.4.3.2 [requires: pyqt5-plugins>=5.15.4.2.2,<5.15.4.3]
```

**Comment by altendky** [comment]
Being addressed (finally, sorry) in https://github.com/altendky/qt-tools/pull/11.

**Comment by MHendricks** [comment]
Thanks 🎉
